/**
 * CSV rendering for the export endpoint and the scheduled report job.
 *
 * CSV is `text/csv; charset=utf-8` with a UTF-8 BOM so Excel opens accented
 * supplier names correctly. `papaparse` handles quoting/escaping.
 */
import Papa from 'papaparse';
import { roundTo } from '@/lib/normalize';
import { hierarchyRows, type ReportDataset } from '@/services/reporting/aggregate';

export type CsvExportOptions = {
  /** Emit a `#`-prefixed metadata preamble (ignored by spreadsheet readers). */
  includeMetadata?: boolean;
  /** Include the extra enrichment/classification columns. */
  verbose?: boolean;
};

/** Column order for the supplier-level CSV. */
export const SUPPLIER_CSV_COLUMNS = [
  'supplier_id',
  'supplier_name',
  'domain',
  'industry',
  'naics',
  'sic',
  'country',
  'unspsc_code',
  'segment',
  'family',
  'class',
  'commodity',
  'confidence',
  'inherited_from_parent',
  'reviewed',
  'llm_model',
  'reasoning',
  'parent_id',
  'parent_name',
  'is_parent',
  'subsidiary_count',
  'parent_source',
  'total_amount',
  'currency',
  'transaction_count',
  'enriched_at',
  'stale',
  'stale_reason',
  'created_at',
  'updated_at',
] as const;

export const PARENT_ROLLUP_CSV_COLUMNS = [
  'parent_id',
  'parent_name',
  'parent_domain',
  'is_virtual_parent',
  'unspsc_code',
  'confidence',
  'supplier_count',
  'subsidiary_count',
  'total_amount',
  'stale_count',
  'low_confidence_count',
] as const;

export const SEGMENT_CSV_COLUMNS = [
  'segment_code',
  'segment',
  'suppliers',
  'spend',
  'spend_share_percent',
  'avg_confidence',
] as const;

export const LOW_CONFIDENCE_CSV_COLUMNS = [
  'supplier_id',
  'supplier_name',
  'unspsc_code',
  'commodity',
  'confidence',
  'parent_name',
  'llm_model',
  'reasoning',
  'total_amount',
] as const;

function toCsv(rows: Array<Record<string, unknown>>, columns: readonly string[]): string {
  return Papa.unparse(
    { fields: [...columns], data: rows.map((row) => columns.map((column) => row[column] ?? '')) },
    { quotes: false, newline: '\r\n' },
  );
}

/** Metadata preamble: filter provenance for anyone opening the raw file. */
function metadataLines(dataset: ReportDataset): string {
  const lines = [
    `# UNSPSC Spend Report: ${dataset.meta.name}`,
    `# Generated at: ${dataset.meta.generatedAt}`,
    `# Generated by: ${dataset.meta.generatedBy}`,
    `# UNSPSC taxonomy version: ${dataset.meta.taxonomyVersion}`,
    `# Rollup: ${dataset.meta.rollup}`,
    `# Filters: ${dataset.meta.filterSummary.length ? dataset.meta.filterSummary.join('; ') : 'none'}`,
    `# Totals: suppliers=${dataset.summary.totalSuppliers} spend=${dataset.summary.totalSpend} classified=${dataset.summary.classified} (${dataset.summary.percentClassified}%) low_confidence=${dataset.summary.lowConfidence} (${dataset.summary.percentLowConfidence}%)`,
  ];
  return `${lines.join('\r\n')}\r\n`;
}

/**
 * Supplier-level CSV. When `rollup === 'parent'`, a parent roll-up section is
 * appended after the detail section, separated by a blank line and a title row,
 * so one file answers both questions.
 */
export function renderSupplierCsv(dataset: ReportDataset, options: CsvExportOptions = {}): string {
  const rows = dataset.rows.map((row) => {
    const supplier = row.supplier;
    const classification = supplier.classification;
    return {
      supplier_id: supplier.id,
      supplier_name: supplier.name,
      domain: supplier.domain ?? '',
      industry: supplier.industry ?? '',
      naics: supplier.naics ?? '',
      sic: supplier.sic ?? '',
      country: supplier.country ?? '',
      unspsc_code: row.effectiveCode ?? '',
      segment: classification?.segment ?? '',
      family: classification?.family ?? '',
      class: classification?.className ?? '',
      commodity: row.commodity ?? '',
      confidence: row.confidence === null ? '' : roundTo(row.confidence, 2),
      inherited_from_parent: classification?.inheritedFromParent ? 'true' : 'false',
      reviewed: classification?.reviewed ? 'true' : 'false',
      llm_model: classification?.llmModel ?? '',
      reasoning: (classification?.reasoning ?? '').replace(/\s+/g, ' ').trim(),
      parent_id: supplier.parentId ?? '',
      parent_name: row.parentLabel === 'Independent' ? '' : row.parentLabel,
      is_parent: supplier.isParent ? 'true' : 'false',
      subsidiary_count: supplier.subsidiaryCount,
      parent_source: supplier.parentSource ?? '',
      total_amount: roundTo(supplier.totalAmount, 2),
      currency: supplier.currency,
      transaction_count: supplier.transactionCount,
      enriched_at: supplier.enrichedAt ?? '',
      stale: supplier.stale ? 'true' : 'false',
      stale_reason: supplier.staleReason ?? '',
      created_at: supplier.createdAt,
      updated_at: supplier.updatedAt,
    };
  });

  const detailColumns = options.verbose
    ? SUPPLIER_CSV_COLUMNS
    : SUPPLIER_CSV_COLUMNS.filter(
        (column) => !['sic', 'country', 'subsidiary_count', 'parent_source', 'stale_reason'].includes(column),
      );

  let output = '';
  if (options.includeMetadata ?? true) output += metadataLines(dataset);
  output += toCsv(rows, detailColumns);

  // Segment + parent sections make the single file self-contained.
  output += `\r\n\r\n# Segment breakdown\r\n`;
  output += toCsv(
    dataset.segments.map((segment) => ({
      segment_code: segment.segmentCode,
      segment: segment.segment,
      suppliers: segment.suppliers,
      spend: segment.spend,
      spend_share_percent: segment.spendShare,
      avg_confidence: segment.avgConfidence ?? '',
    })),
    SEGMENT_CSV_COLUMNS,
  );

  if (dataset.meta.rollup === 'parent' || dataset.parents.some((parent) => parent.subsidiaryCount > 0)) {
    output += `\r\n\r\n# Parent roll-up\r\n`;
    output += toCsv(
      dataset.parents.map((parent) => ({
        parent_id: parent.parentId ?? '',
        parent_name: parent.parentName,
        parent_domain: parent.parentDomain ?? '',
        is_virtual_parent: parent.isVirtualRoot ? 'true' : 'false',
        unspsc_code: parent.unspscCode ?? '',
        confidence: parent.confidence === null ? '' : roundTo(parent.confidence, 2),
        supplier_count: parent.supplierCount,
        subsidiary_count: parent.subsidiaryCount,
        total_amount: roundTo(parent.totalAmount, 2),
        stale_count: parent.staleCount,
        low_confidence_count: parent.lowConfidenceCount,
      })),
      PARENT_ROLLUP_CSV_COLUMNS,
    );
  }

  if (dataset.lowConfidence.length) {
    output += `\r\n\r\n# Low-confidence review appendix\r\n`;
    output += toCsv(
      dataset.lowConfidence.map((row) => ({
        supplier_id: row.supplierId,
        supplier_name: row.name,
        unspsc_code: row.code ?? '',
        commodity: row.commodity ?? '',
        confidence: row.confidence === null ? '' : roundTo(row.confidence, 2),
        parent_name: row.parentName ?? '',
        llm_model: row.model ?? '',
        reasoning: (row.reasoning ?? '').replace(/\s+/g, ' ').trim(),
        total_amount: roundTo(row.spend, 2),
      })),
      LOW_CONFIDENCE_CSV_COLUMNS,
    );
  }

  return output;
}

/** Parent-only CSV (used by the `/hierarchy` export button). */
export function renderParentRollupCsv(dataset: ReportDataset): string {
  return toCsv(
    dataset.parents.map((parent) => ({
      parent_id: parent.parentId ?? '',
      parent_name: parent.parentName,
      parent_domain: parent.parentDomain ?? '',
      is_virtual_parent: parent.isVirtualRoot ? 'true' : 'false',
      unspsc_code: parent.unspscCode ?? '',
      confidence: parent.confidence === null ? '' : roundTo(parent.confidence, 2),
      supplier_count: parent.supplierCount,
      subsidiary_count: parent.subsidiaryCount,
      total_amount: roundTo(parent.totalAmount, 2),
      stale_count: parent.staleCount,
      low_confidence_count: parent.lowConfidenceCount,
    })),
    PARENT_ROLLUP_CSV_COLUMNS,
  );
}

/** Hierarchy CSV: one row per parent/subsidiary edge. */
export function renderHierarchyCsv(dataset: ReportDataset): string {
  const rows = hierarchyRows(dataset).flatMap((parent) => {
    if (!parent.subsidiaries.length) {
      return [
        {
          parent_name: parent.parentName,
          parent_code: parent.parentCode ?? '',
          role: 'parent',
          supplier_name: parent.parentName,
          unspsc_code: parent.parentCode ?? '',
          confidence: '',
          amount: parent.totalAmount,
          cluster_total_amount: parent.totalAmount,
        },
      ];
    }
    return [
      {
        parent_name: parent.parentName,
        parent_code: parent.parentCode ?? '',
        role: 'parent',
        supplier_name: parent.parentName,
        unspsc_code: parent.parentCode ?? '',
        confidence: '',
        amount: '',
        cluster_total_amount: parent.totalAmount,
      },
      ...parent.subsidiaries.map((subsidiary) => ({
        parent_name: parent.parentName,
        parent_code: parent.parentCode ?? '',
        role: 'subsidiary',
        supplier_name: subsidiary.name,
        unspsc_code: subsidiary.code ?? '',
        confidence: subsidiary.confidence === null ? '' : roundTo(subsidiary.confidence, 2),
        amount: roundTo(subsidiary.amount, 2),
        cluster_total_amount: parent.totalAmount,
      })),
    ];
  });

  return toCsv(rows, [
    'parent_name',
    'parent_code',
    'role',
    'supplier_name',
    'unspsc_code',
    'confidence',
    'amount',
    'cluster_total_amount',
  ]);
}

/**
 * Bytes for the HTTP response, with a BOM for Excel compatibility.
 * Returned as a Node `Buffer` so it satisfies `BodyInit` directly.
 */
export function csvBytes(csv: string): Buffer {
  return Buffer.from(`\uFEFF${csv}`, 'utf8');
}

/** Filename-safe slug. */
export function reportFilename(name: string, format: 'csv' | 'pdf', extension?: string): string {
  const slug =
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 80) || 'report';
  return `${slug}.${extension ?? format}`;
}
